### ISSUE TITLE
更新ip rest api

### ISSUE THREAD

**Issue by frozenpenguin** [xiaoicx/ddns-dnspod-script#1]
ip库的api改了，/outGetIpInfo?ip=[ip地址字串]&accessKey=[访问密匙]
还有开头改为/bin/bash, if [ A == B ]在sh上会有问题
ubuntu的sh是bash，但在其他发行版会有问题

**Comment by xiaoicx** [comment]
已重构,有问题可以重新开启此Issues.感谢您的支持和使用.
